name: 'JMR'
services:
  jmr_frontend:
    container_name: jmr_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - API_BASE=http://jmr_backend:7749
    ports:
      - 5173:5173
    depends_on:
      - jmr_backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  jmr_backend:
    container_name: jmr_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 7749:7749

